%dev.quarkus.http.port=8086

quarkus.index-dependency.shared-quarkus.artifact-id=shared-quarkus
quarkus.index-dependency.shared-quarkus.group-id=es.upsa.ssi

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true

service.equipos.url=http://equipos:8080
service.jugadores.url=http://jugadores:8080
service.contratos.url=http://contratos:8080

%dev.service.equipos.url=http://localhost:8082
%dev.service.jugadores.url=http://localhost:8083
%dev.service.contratos.url=http://localhost:8084

rest.client.equipos/mp-rest/url=${service.equipos.url}
rest.client.jugadores/mp-rest/url=${service.jugadores.url}
rest.client.contratos/mp-rest/url=${service.contratos.url}

quarkus.smallrye-health.root-path=/contratos/health

quarkus.smallrye-openapi.servers=/aggregator
quarkus.swagger-ui.urls.aggregator=/aggregator/contratos/openapi
quarkus.smallrye-openapi.path=/contratos/openapi

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/contratos/swagger-ui


redis.hosts=localhost
redis.port=6379
redis.password=password


quarkus.redis.hosts=redis://${redis.hosts}:${redis.port}
quarkus.redis.client-type=standalone
quarkus.redis.password=${redis.password}

quarkus.cache.redis."aggregator".key-type=java.lang.String
quarkus.cache.redis."aggregator".value-type=java.lang.String