%dev.quarkus.http.port=8084

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true



database.host=localhost
database.port=5432
database.name=upsa
database.username=system
database.password=manager

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${database.username}
quarkus.datasource.password=${database.password}
quarkus.datasource.jdbc.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}

quarkus.index-dependency.shared-quarkus.artifact-id=shared-quarkus
quarkus.index-dependency.shared-quarkus.group-id=es.upsa.ssi

quarkus.smallrye-health.root-path=/contratos/health

quarkus.smallrye-openapi.path=/contratos/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/contratos/swagger-ui


redis.hosts=localhost
redis.port=6379
redis.password=password


quarkus.redis.hosts=redis://${redis.hosts}:${redis.port}
quarkus.redis.client-type=standalone
quarkus.redis.password=${redis.password}

quarkus.cache.redis."contratos".key-type=java.lang.String
quarkus.cache.redis."contratos".value-type=java.lang.String