worker_processes auto;

events {
    worker_connections 1024;
}

http
{
    upstream ups_equipos
    {
       server equipos:8080;
    }
    upstream ups_jugadores
    {
       server jugadores:8080;
    }
    upstream ups_contratos
    {
       server contratos:8080;
    }
    upstream ups_aggregator
    {
       server aggregator:8080;
    }

    server
    {
        listen 80;
        server_name xxx.upsa.es;

        location /equipos
        {
            proxy_pass http://ups_equipos;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /jugadores
        {
            proxy_pass http://ups_jugadores;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /contratos
        {
            proxy_pass http://ups_contratos;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /aggregator/
        {
            proxy_pass http://ups_aggregator/;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix /aggregator;
            proxy_set_header X-Real-IP $remote_addr;
        }


    }


}

